diamond blastx -d  reference/diamond/seqs -q data/raw/Control-1_R1_001.fastq.gz -o outputs/101/Control-1-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/Control-2_R1_001.fastq.gz -o outputs/101/Control-2-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/Control-2_R1_001.fastq.gz -o outputs/101/Control-3-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/NUP-1_R1_001.fastq.gz -o outputs/101/NUP-1-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/NUP-2_R1_001.fastq.gz -o outputs/101/NUP-2-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/NUP-3_R1_001.fastq.gz -o outputs/101/NUP-3-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/PVT-1_R1_001.fastq.gz -o outputs/101/PVT-1-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/PVT-2_R1_001.fastq.gz -o outputs/101/PVT-2-diamond
diamond blastx -d  reference/diamond/seqs -q data/raw/PVT-3_R1_001.fastq.gz -o outputs/101/PVT-3-diamond
