---
title: "206-volcano-plots"
output: html_document
date: "2023-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}
library(tidyverse)
library(ggrepel)
library(DESeq2)
library(pheatmap)
library(viridis)
library(RColorBrewer)
library(textshape)
```

Set up automatic making of DE testing and volcano plots

```{r}
meta<-read_csv("meta/rna-seq-meta.csv")
```

```{r}
dat<-read_csv("data/raw_counts-intronic-intergenic.csv") %>% select(-Gene.name) %>%
  relocate(ID) %>% dplyr::rename(gene_id=ID)

```

```{r}
locus<-c("AAVS1","Dep.2","Dep.55","Prot.218","Dep.3","Ap.102")
```

Colors for pheatmap 
Gene names if needed
```{r}
#ramp<-viridis(8, option="plasma", direction = -1)
ramper<-colorRampPalette(c("white", "darkred"))
ramp<-ramper(8)
namesdf<-read_csv("data/raw_counts-intronic-intergenic.csv") %>% select(ID, Gene.name) 
```

```{r}
Tester<-function(locus, meta, dat) {
coldata<-meta %>% filter(Locus==locus) %>% select(Sample, Category, Donor, Locus)
coldata2<-meta %>% filter(Category=="Control") %>% filter(Donor %in% coldata$Donor) %>% select(Sample, Category, Donor, Locus)

m<-bind_rows(coldata,coldata2)
m$Category <- factor(m$Category, levels=c("Control","Edited"))
m$Donor <- factor(m$Donor)
m<-as.data.frame(m)
rownames(m)<-m$Sample
m<-m %>% select(-Sample)


d<-select(dat, gene_id, rownames(m)) 
d<-as.data.frame(d)
rownames(d)<-d$gene_id
d<-d %>% select(-gene_id)

dds <- DESeqDataSetFromMatrix(countData = d,
                              colData = m,
                              design = ~Donor + Category )

#Drop low counts
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

#Create other data
vsd <- vst(dds, blind=FALSE)
ntd <- normTransform(dds)


ntddata<-assay(ntd)
vsddata<-assay(vsd)

#PCA for fun 
pcaData <- plotPCA(vsd, intgroup=c("Category", "Donor"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))

ggplot(pcaData, aes(PC1, PC2, fill=Donor, shape=Category)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed() +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  scale_fill_viridis_d(option="magma") +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(override.aes=list(shape=c(22)))) +
  ggtitle(paste0(locus, "\n")) +
  theme(plot.title = element_text(hjust=0.5, size=16, face="bold")) 

ggsave(paste0("outputs/206/",locus,"-pca.pdf"))

#DE testing

dds <- DESeq(dds)
res <- results(dds)

resOrdered <- res[order(res$pvalue),]
summary(res)

results<-as_tibble(resOrdered)
results$Gene<-rownames(resOrdered)
results<-results %>% relocate(Gene) %>% filter(padj<0.05, abs(log2FoldChange) >= 1) %>% mutate(Locus=paste0(locus))

write_csv(results, paste0("outputs/206/",locus,"-results.csv"))
color<-ifelse(locus=="AAVS1", "grey",
       ifelse(locus %in% c("Dep.3","Ap.102"), "red","blue"))

ggplot() +
  geom_point(data=results %>% filter(padj < 0.01), aes(x=log2FoldChange, y=-log10(padj)),
             color=color, alpha=0.9) +
  geom_point(data=results %>% filter(padj >= 0.01), aes(x=log2FoldChange, y=-log10(padj)),
             color="black", alpha=0.9) +
  xlab("log2 (Fold Change)") +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  ggtitle(paste0(locus, "\n")) +
  theme(plot.title = element_text(hjust=0.5, size=16, face="bold")) +
  theme(axis.title = element_text(face="bold")) +
  xlim(-12,12) +
  ylim(0,70)

ggsave(paste0("outputs/206/",locus,"-volcano.jpeg"), width=5, height=4)

# Heatmap of all DE genes
# need normalized counts
ntd <- normTransform(dds)
assay<-assay(ntd)
norm<-counts(dds,normalized=TRUE)
res<-norm[rownames(norm) %in% results$Gene,]

ddf <- as.data.frame(colData(dds)[,c("Category","Donor")])

pdf(paste0("outputs/206/",locus,"-heatmap.pdf"), width=8, height=10)

anno<-ifelse(locus=="AAVS1", "grey",
       ifelse(locus %in% c("Dep.3","Ap.102"), "red","blue"))

annotate = list(
  Category = c(Control="grey50", Edited=paste0(anno)))

pheatmap(assay[rownames(assay) %in% rownames(res),], cluster_rows=TRUE, show_rownames=FALSE,
         cluster_cols=TRUE, annotation_col=ddf,
         color=ramp, annotation_colors = annotate)

dev.off()


#subset to top genes.... based on padj    
#get names    

toppers<-results %>% top_n(20, -padj)

## get genes for insertion sites or for flanking genes
  if (locus=="AAVS1") {
  gen<-c("ENSG00000125503")
} else if (locus=="Dep.2") {
  gen<-c("ENSG00000164627")
} else if (locus=="Dep.55") {
  gen<-c("ENSG00000124243")
} else if (locus=="Prot.218") {
  gen<-c("ENSG00000136960")
} else if (locus=="Dep.3") {
  gen<-c("ENSG00000136243","ENSG00000136235")
} else if (locus=="Ap.102") {
  gen<-c("ENSG00000249859","ENSG00000229140")
}

rename<-assay %>% as_tibble() 
rename$ID<-rownames(assay) 
rename<- rename %>% filter(ID %in% c(toppers$Gene, gen))
rename<-rename %>% left_join(namesdf)

r2<-rename %>% filter(ID %in% c(gen)) # this so I can order the matrix later

# needs to be a matrix and reordered control, edited
#locus<-c("AAVS1","Dep.2","Dep.55","Prot.218","Dep.3","Ap.102")

  if (locus=="AAVS1") {
  order<-c("Control.1","KIF6.1","AAVS1.1","AAVS1.2")
} else if (locus=="Dep.2") {
  order<-c("Control.1","KIF6.1","Control.2","KIF6.2")
} else if (locus=="Dep.55") {
  order<-c("Control1","Control2","BCAS1","BCAS2")
} else if (locus=="Prot.218") {
  order<-c("Control1","Control2","ENPP1","ENPP2")
} else if (locus=="Dep.3") {
  order<-c("Control-1","Control-2","NUP1","NUP2")
} else if (locus=="Ap.102") {
  order<-c("Control-1","Control-2","PVT1","PVT2")
}

matrix<-rename %>% select(-ID, -Gene.name)  %>% relocate(all_of(order)) %>% as.matrix()
rownames(matrix) <- rename$Gene.name

#Reorder matrix, append flanking/edited genes

matrix<-matrix[order(rowSums(matrix[,3:4]),decreasing=T),]

m1<-subset(matrix, !(rownames(matrix) %in% r2$Gene.name))
m2<-subset(matrix, rownames(matrix) %in% r2$Gene.name)
matrix<-rbind(m1,m2)

pdf(paste0("outputs/206/",locus,"-heatmap-sub.pdf"), width=2.5, height=6)

pheatmap(matrix, 
         cluster_rows=FALSE, show_rownames=TRUE,border_color = NA,
         cluster_cols=FALSE, show_colnames=FALSE, annotation_col=ddf,
         color=ramp, annotation_colors = annotate, legend=FALSE,
         main = paste0(locus,"\n"), 
         annotation_legend=FALSE)

dev.off()


}
```


## Here is for trialling data
```{r, eval=FALSE}
locus<-c("Dep.2")
ntd <- normTransform(dds)
assay<-assay(ntd)
norm<-counts(dds,normalized=TRUE)
res<-norm[rownames(norm) %in% results$Gene,]

ddf <- as.data.frame(colData(dds)[,c("Category","Donor")])

#pdf(paste0("outputs/206/",locus,"-heatmap.pdf"), width=8, height=10)

anno<-ifelse(locus=="AAVS1", "grey",
       ifelse(locus %in% c("Dep.3","Ap.102"), "red","blue"))

annotate = list(
  Category = c(Control="grey50", Edited=paste0(anno)))

#dev.off()

#subset to top genes.... based on padj    
#get names    

toppers<-results %>% top_n(20, -padj) 

## get genes
  if (locus=="AAVS1") {
  gen<-c("ENSG00000125503")
} else if (locus=="Dep.2") {
  gen<-c("ENSG00000164627")
} else if (locus=="Dep.55") {
  gen<-c("ENSG00000124243")
} else if (locus=="Prot.218") {
  gen<-c("ENSG00000136960")
} else if (locus=="Dep.3") {
  gen<-c("ENSG00000136243","ENSG00000136235")
} else if (locus=="Ap.102") {
  gen<-c("ENSG00000249859","ENSG00000229140")
}

rename<-assay %>% as_tibble() 
rename$ID<-rownames(assay) 
rename<- rename %>% filter(ID %in% c(toppers$Gene, gen))
rename<-rename %>% left_join(namesdf)

r2<-rename %>% filter(ID %in% c(gen))
# needs to be a matrix and reorderd control, edited
  if (locus=="AAVS1") {
  order<-c("Control.1","KIF6.1","AAVS1.2","AAVS1.1")
} else if (locus=="Dep.2") {
  order<- c("Control.1","KIF6.1","Control.2","KIF6.2")
}


matrix<-rename %>% select(-ID, -Gene.name)  %>% relocate(all_of(order)) %>% as.matrix()
rownames(matrix) <- rename$Gene.name

#matrix<-matrix[order(rowSums(matrix[,3:4]),decreasing=T),]
#matrix<-matrix[order(rowSums(matrix),decreasing=T),]
matrix<-cluster_matrix(matrix, dim=c("row"))
m1<-subset(matrix, !(rownames(matrix) %in% r2$Gene.name))
m2<-subset(matrix, rownames(matrix) %in% r2$Gene.name)
matrix<-rbind(m1,m2)

pheatmap(matrix, 
         cluster_rows=FALSE, show_rownames=TRUE, border_color = NA,
         cluster_cols=FALSE, show_colnames=FALSE, annotation_col=ddf,
         color=ramp, annotation_colors = annotate, legend=TRUE,
         main = paste0(locus,"\n"), 
         annotation_legend=FALSE)


#ggplot version
#df<-rename %>% select(-ID)  %>% relocate(all_of(order)) %>% relocate(Gene.name)
#ddf<-pivot_longer(df, 2:5, names_to = "Sample", values_to = "Expression")
#ggplot(ddf)+geom_tile(aes(x=Sample, y=Gene.name, fill=Expression))
```

```{r}
lapply(locus, Tester, meta, dat)
```

## Summarize 

```{r}
resfiles<-list.files(path="outputs/206/", pattern="*results.csv", full.names = TRUE)

resf<-lapply(resfiles,read_csv) %>% bind_rows()
```

```{r}
sum<-resf %>% mutate(Direction=ifelse(log2FoldChange < 0, "Negative", "Positive")) %>% group_by(Locus, Direction) %>%
                  summarize(Count=n())
sum<-sum %>% mutate(Number=ifelse(Direction=="Positive",Count,-1*Count))
sum
```

Make barplot of this.
Add consistently DE genes to the plot, in a stacked fashion

```{r}
universal<-resf %>% mutate(Direction=ifelse(log2FoldChange < 0, "Negative", "Positive")) %>% group_by(Gene) %>% mutate(Occurrence=n()) %>% filter(Occurrence == 6) %>% select(Gene, Direction, Occurrence) %>% unique()

unis<-universal %>% group_by(Direction) %>% summarize(Consistent=n()) %>%
  mutate(Consistent=ifelse(Direction=="Positive",Consistent, -1*Consistent))
write_csv(universal, file="outputs/206/genes-found-across-comparisions.csv")
```


```{r}
sum2<-sum %>% left_join(unis) 
sum2<-sum2 %>% left_join(meta)
sum2$Locus<-factor(sum2$Locus, levels=c("AAVS1","Ap.102","Dep.3","Dep.2","Dep.55","Prot.218"))
sum2<-mutate(sum2,Fill=ifelse(Locus=="AAVS1", "grey",
       ifelse(Locus %in% c("Dep.3","Ap.102"), "red","blue")))
```

```{r}
ggplot(sum2) +
  geom_bar(aes(x=Locus,y=Number), fill=sum2$Fill, stat='identity', alpha=0.6, 
           width=0.8) +
  geom_bar(aes(x=Locus,y=Consistent), fill=sum2$Fill, stat='identity', alpha=0.8, 
           width=0.8) +
  scale_fill_viridis_d(option="H") +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  ylab("Number DE Genes\n") +
  xlab("\nLocus") +
  theme(axis.title = element_text(face = "bold"))+
  theme(legend.position = "none") +
  ylim(-1500,1500) 
ggsave("outputs/206/de-genes.jpeg", width=5, height=5)
```
